<?php

function override_apache_init() {
  global $base_root;
  
  
  $CUrl = $_SERVER['REQUEST_URI'];
  preg_match("/search\/site\/c/", $CUrl, $MUrl);
  preg_match("/search\/site\/\//", $CUrl, $MUrl2);
  
  if( count($MUrl) == 1 && count($MUrl2) == 0){
    $CUrl = str_replace('search/site/c/', 'search/site//c/', $CUrl);
    drupal_goto($base_root.$CUrl);
  }
  
  /**/
  preg_match("/search\/site\/b/", $CUrl, $MUrl);
  preg_match("/search\/site\/\//", $CUrl, $MUrl2);
  
  if( count($MUrl) == 1 && count($MUrl2) == 0){
    $CUrl = str_replace('search/site/b/', 'search/site//b/', $CUrl);
    drupal_goto($base_root.$CUrl);
  }
  
  /**/
  preg_match("/search\/site\/r/", $CUrl, $MUrl);
  preg_match("/search\/site\/\//", $CUrl, $MUrl2);
  
  if( count($MUrl) == 1 && count($MUrl2) == 0){
    $CUrl = str_replace('search/site/r/', 'search/site//r/', $CUrl);
    drupal_goto($base_root.$CUrl);
  }
  
  
  /*Taxonomy url rewrite*/
  $termId = arg(2);
  preg_match("/taxonomy\/term\/$termId\/c/", $CUrl, $MUrl);
  preg_match("/taxonomy\/term\/$termId\/\//", $CUrl, $MUrl2);
  
  if( count($MUrl) == 1 && count($MUrl2) == 0){
    $CUrl = str_replace("taxonomy/term/$termId/c", "taxonomy/term/$termId//c", $CUrl);
    drupal_goto($base_root.$CUrl);
  }
  
  /**/
  preg_match("/taxonomy\/term\/$termId\/b/", $CUrl, $MUrl);
  preg_match("/taxonomy\/term\/$termId\/\//", $CUrl, $MUrl2);
  
  if( count($MUrl) == 1 && count($MUrl2) == 0){
    $CUrl = str_replace("taxonomy/term/$termId/b", "taxonomy/term/$termId//b", $CUrl);
    drupal_goto($base_root.$CUrl);
  }
  
  /**/
  preg_match("/taxonomy\/term\/$termId\/r/", $CUrl, $MUrl);
  preg_match("/taxonomy\/term\/$termId\/\//", $CUrl, $MUrl2);
  
  if( count($MUrl) == 1 && count($MUrl2) == 0){
    $CUrl = str_replace("taxonomy/term/$termId/r", "taxonomy/term/$termId//r", $CUrl);
    drupal_goto($base_root.$CUrl);
  }
  
}

function override_apache_menu(){
  $items = array();
  
  $items['add_custom_url'] = array(
    'title' => t('override apache add custom url'),
    'page callback' => 'override_apache_add_custom_url',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}  


function override_apache_add_custom_url(){
  
  //override_apache_add_retailer();
  //override_apache_add_brand();  
  //override_apache_add_category();
  
  db_query("delete from xmlsitemap where type = 'custom'");
  
  //override_apache_add_retailer_band();
  //override_apache_add_retailer_category();
  override_apache_add_band_category();
  
  return 'ok';
}

function override_apache_cron(){
  override_apache_add_custom_url();  
}

/*create url for taxonomy retailer*/
function override_apache_add_retailer(){
  
  $QGetRetailer = db_query("SELECT name, tid FROM {taxonomy_term_data} WHERE vid = 2 ");
  
  while( $RGetRetailer = $QGetRetailer->fetchObject() ){
      
      $TermName = override_apache_modify_title(strtolower($RGetRetailer->name));
      $TermId = $RGetRetailer->tid;
      
      $loc = "search/site//r/$TermName-$TermId";
      
      $QCount = db_query( "SELECT count(id) as total FROM xmlsitemap WHERE type = 'custom' and loc like '$loc' ");
      $RCount = $QCount->fetchObject();
      
      if( $RCount->total == 0 ){
        $link = array('type' => 'custom',
                    'id' => db_query("SELECT MAX(id) FROM {xmlsitemap} WHERE type = 'custom'")->fetchField() + 1,
                    'loc' => $loc,
                    'priority' => 0.5,
                    'changefreq' => 0,
                    'language' => 'und'    
        );
        xmlsitemap_link_save($link);
      }
  }
  
}

/*create url for taxonomy brand*/
function override_apache_add_brand(){
  
  //$QGetRetailer = db_query("SELECT name, tid FROM {taxonomy_term_data} WHERE vid = 4 group by name ");
  $QGetRetailer = db_query("SELECT name, tid 
                            FROM taxonomy_term_data d INNER JOIN field_data_field_create_combination c ON d.tid = c.entity_id
                            WHERE d.vid = 4 and c.field_create_combination_value = 'Yes' ");

  while( $RGetRetailer = $QGetRetailer->fetchObject() ){
      
      $TermName = override_apache_modify_title(strtolower($RGetRetailer->name));
      $TermId = $RGetRetailer->tid;
      
      $loc = "search/site//b/$TermName-$TermId";
      
      $QCount = db_query( "SELECT count(id) as total FROM xmlsitemap WHERE type = 'custom' and loc like '$loc' ");
      $RCount = $QCount->fetchObject();
      
      if( $RCount->total == 0 ){
        $link = array('type' => 'custom',
                    'id' => db_query("SELECT MAX(id) FROM {xmlsitemap} WHERE type = 'custom'")->fetchField() + 1,
                    'loc' => $loc,
                    'priority' => 0.5,
                    'changefreq' => 0,
                    'language' => 'und'    
        );
        xmlsitemap_link_save($link);
      }
  }
  
}

/*create url for taxonomy category*/
function override_apache_add_category(){
  
  $QGetRetailer = db_query("SELECT name, tid FROM {taxonomy_term_data} WHERE vid = 3 group by name ");
  while( $RGetRetailer = $QGetRetailer->fetchObject() ){
      
      $TermName = override_apache_modify_title(strtolower($RGetRetailer->name));
      $TermId = $RGetRetailer->tid;
      
      $loc = "search/site//c/$TermName-$TermId";
      
      $QCount = db_query( "SELECT count(id) as total FROM xmlsitemap WHERE type = 'custom' and loc like '$loc' ");
      $RCount = $QCount->fetchObject();
      
      
      
      if( $RCount->total == 0 ){
        $link = array('type' => 'custom',
                    'id' => db_query("SELECT MAX(id) FROM {xmlsitemap} WHERE type = 'custom'")->fetchField() + 1,
                    'loc' => $loc,
                    'priority' => 0.5,
                    'changefreq' => 0,
                    'language' => 'und'    
        );
        xmlsitemap_link_save($link);
      }
  }
  
  
   
}

function override_apache_add_retailer_band(){
  global $base_root;
  
  $QGetRetailer = db_query("SELECT name, tid FROM {taxonomy_term_data} WHERE vid = 2 ");
  
  while( $RGetRetailer = $QGetRetailer->fetchObject() ){
      //if($RGetRetailer->tid == 4){
        //set of code written for brand url  
        $TermName = override_apache_modify_title(strtolower($RGetRetailer->name));
        $TermId = $RGetRetailer->tid;
        $Rloc = "/r/$TermName-$TermId";
        
        $cnt = 1;
        //set of code written for retailer url
        
        $QGetBrand = db_query("SELECT d.name, d.tid
                              FROM taxonomy_term_data d INNER JOIN field_data_field_create_combination c ON d.tid = c.entity_id
                              WHERE d.vid = 4 and c.field_create_combination_value = 'Yes' and d.name!='' group by d.name  ");
        
                            
        while( $RGetBrand = $QGetBrand->fetchObject() ){
          $BTermId = $RGetBrand->tid;
          $total_record = override_apache_get_total($TermId, $BTermId);
     
            if($total_record > 0){
              $BrandName = override_apache_modify_title(strtolower($RGetBrand->name));
              
              $loc = $base_root . base_path() . "search/site//b/$BrandName-$BTermId".$Rloc;
              
              $QCount = db_query( "SELECT count(id) as total FROM xmlsitemap WHERE type = 'custom' and loc like '$loc' ");
              $RCount = $QCount->fetchObject();
              
              if( $RCount->total == 0 ){
                $link = array('type' => 'custom',
                            'id' => db_query("SELECT MAX(id) FROM {xmlsitemap} WHERE type = 'custom'")->fetchField() + 1,
                            'loc' => $loc,
                            'priority' => 0.5,
                            'changefreq' => 0,
                            'language' => 'und'    
                );
                xmlsitemap_link_save($link);
              }
            }
        }
  }
}

function override_apache_add_band_category(){
    global $base_root;
  
  //$QGetBrand = db_query("SELECT name, tid FROM {taxonomy_term_data} WHERE vid = 4 group by name ");
  
  $QGetBrand = db_query("SELECT d.name, d.tid
                        FROM taxonomy_term_data d INNER JOIN field_data_field_create_combination c ON d.tid = c.entity_id
                        WHERE d.vid = 4 and c.field_create_combination_value = 'Yes' group by d.name ");
                            
  while( $RGetBrand = $QGetBrand->fetchObject() ){
      
      $BrandName = override_apache_modify_title(strtolower($RGetBrand->name));
      $TermId = $RGetBrand->tid;
      
      $totalBrand = override_apache_get_total( '', $TermId );
      if( $totalBrand > 0 ){
        $CombPath = $base_root . base_path() . "search/site//b/$BrandName-$TermId";
        
        $QGetCategory = db_query("SELECT d.name, d.tid
                                  FROM taxonomy_term_data d INNER JOIN  taxonomy_term_hierarchy h ON d.tid = h.tid
                                  WHERE d.vid = 3 and  h.parent = 0");
        while( $RGetCategory = $QGetCategory->fetchObject() ){
          $totalParent = override_apache_get_Ptotal( $RGetCategory->tid, $TermId );
          if( $totalParent > 0 ){
            $CateParentName = '/c/'.override_apache_modify_title(strtolower($RGetCategory->name));
            $CateParentId = $RGetCategory->tid;
            
            $CombPath2 = $CombPath . $CateParentName.'-'.$CateParentId;
            //override_apache_add_url( $CombPath2 );   
            /*************************************/
            $QGetCCategory = db_query("SELECT d.name, d.tid
                                  FROM taxonomy_term_data d INNER JOIN  taxonomy_term_hierarchy h ON d.tid = h.tid
                                  WHERE d.vid = 3 and  h.parent = '$CateParentId' ");
            while( $RGetCCategory = $QGetCCategory->fetchObject() ){
              
              //passing category id and brand id
              //echo $RGetCCategory->tid .'---'. $TermId.'==';
              $Ptid = $RGetCCategory->tid;
              $totalChild = override_apache_get_Ptotal( $RGetCCategory->tid, $TermId );
              
              if( $totalChild > 0 ){
                
                $CateChildName = '/c/'.override_apache_modify_title(strtolower($RGetCCategory->name));
                $CateChildId = $RGetCCategory->tid;
                
                override_apache_add_url( $CombPath2 );
                $CombPath3 = $CombPath2 . $CateChildName.'-'.$CateChildId;
                override_apache_add_url( $CombPath3 );
                
                /******************sub sub category links********************************/
                $QGetSubCCategory = db_query("SELECT d.name, d.tid
                                  FROM taxonomy_term_data d INNER JOIN  taxonomy_term_hierarchy h ON d.tid = h.tid
                                  WHERE d.vid = 3 and  h.parent = '$CateChildId' ");
                while( $RGetSubCCategory = $QGetSubCCategory->fetchObject() ){
                  
                  //passing category id and brand id
                  //echo $RGetCCategory->tid .'---'. $TermId.'==';
                  $SubCateID = $RGetSubCCategory->tid;                  
                  $totalSubChild = override_apache_get_sub_sub_cate_total( $SubCateID, $TermId );
                  //mail( 'sanjay.kumar1@mail.vinove.com','totalSubChild','totalSubChild===>'.print_r($totalSubChild,1).'-'.$SubCateID.'--'.$Ptid );
                  //die;
                  if( $totalSubChild > 0 ){
                    
                    $CateSubChildName = '/c/'.override_apache_modify_title(strtolower($RGetSubCCategory->name));
                    $CateSubChildId = $RGetSubCCategory->tid;
                    
                    //override_apache_add_url( $CombPath2 );
                    $CombPath4 = $CombPath2 . $CateChildName.'-'.$CateChildId . $CateSubChildName.'-'.$CateSubChildId;
                    
                    //mail( 'sanjay.kumar1@mail.vinove.com','CombPath4','CombPath4===>'.print_r($CombPath4,1) );
                    
                    override_apache_add_url( $CombPath4 );
                  }  
                }
                /***************************************************/
                
              }  
            }  
            /*************************************/            
          }
        }  
      }
  }
}

//combination of retailer and category
function override_apache_add_retailer_category(){
  global $base_root;
  
  //$QGetBrand = db_query("SELECT name, tid FROM {taxonomy_term_data} WHERE vid = 4 group by name limit 20 ");
  
  $QGetBrand = db_query("SELECT name, tid FROM {taxonomy_term_data} WHERE vid = 2 group by name");
  
  while( $RGetBrand = $QGetBrand->fetchObject() ){
      
      $BrandName = override_apache_modify_title(strtolower($RGetBrand->name));
      $TermId = $RGetBrand->tid;
      
      $totalBrand = override_apache_get_total( $TermId, '' );
      
      if( $totalBrand > 0 ){
        //$CombPath = $base_root . base_path() . "search/site//b/$BrandName-$TermId";
        $CombPath = $base_root . base_path() . "search/site//r/$BrandName-$TermId";
        
        $QGetCategory = db_query("SELECT d.name, d.tid
                                  FROM taxonomy_term_data d INNER JOIN  taxonomy_term_hierarchy h ON d.tid = h.tid
                                  WHERE d.vid = 3 and  h.parent = 0");
       
        while( $RGetCategory = $QGetCategory->fetchObject() ){
          //passing category id and retailer id
          $totalParent = override_apache_get_RCURL( $RGetCategory->tid, $TermId );
          
          if( $totalParent > 0 ){
            $CateParentName = '/c/'.override_apache_modify_title(strtolower($RGetCategory->name));
            $CateParentId = $RGetCategory->tid;
            
            $CombPath2 = $CombPath . $CateParentName.'-'.$CateParentId;
            /*************************************/
           
            $QGetCCategory = db_query("SELECT d.name, d.tid
                                  FROM taxonomy_term_data d INNER JOIN  taxonomy_term_hierarchy h ON d.tid = h.tid
                                  WHERE d.vid = 3 and  h.parent = '$CateParentId' ");
           
            while( $RGetCCategory = $QGetCCategory->fetchObject() ){
              
              //passing category id and brand id
              //echo $RGetCCategory->tid .'---'. $TermId.'==';
              $totalChild = override_apache_get_RCPtotal( $RGetCCategory->tid, $TermId );
              
              if( $totalChild > 0 ){
                
                $CateChildName = '/c/'.override_apache_modify_title(strtolower($RGetCCategory->name));
                $CateChildId = $RGetCCategory->tid;
                
                override_apache_add_url( $CombPath2 );
                
                $CombPath3 = $CombPath2 . $CateChildName.'-'.$CateChildId;
                override_apache_add_url( $CombPath3 );
                //$CombPath3 = $CombPath2 . $CateChildName.'-'.$CateChildId;
              }  
            }  
            /*************************************/            
          }
        }  
      }
  }
}

function override_apache_add_url( $loc ){
  
  $QCount = db_query( "SELECT count(id) as total FROM xmlsitemap WHERE type = 'custom' and loc like '$loc' ");
  $RCount = $QCount->fetchObject();
  
  if( $RCount->total == 0 ){
    $link = array('type' => 'custom',
                'id' => db_query("SELECT MAX(id) FROM {xmlsitemap} WHERE type = 'custom'")->fetchField() + 1,
                'loc' => $loc,
                'priority' => 0.5,
                'changefreq' => 0,
                'language' => 'und'    
    );
    xmlsitemap_link_save($link);
  }
  
}

function override_apache_get_total( $retailer = '', $brand = '' ){
  
  if( !empty($brand) && !empty($retailer) ){
      
    $query = db_query("SELECT count(node.nid) as total
      FROM 
      {node} node
      LEFT JOIN {field_data_field_brand} field_data_field_brand ON node.nid = field_data_field_brand.entity_id AND (field_data_field_brand.entity_type = 'node' AND field_data_field_brand.deleted = '0')
      LEFT JOIN {field_data_field_retailer} field_data_field_retailer ON node.nid = field_data_field_retailer.entity_id AND (field_data_field_retailer.entity_type = 'node' AND field_data_field_retailer.deleted = '0')
      WHERE (( (field_data_field_brand.field_brand_tid = '$brand' ) AND (field_data_field_retailer.field_retailer_tid = '$retailer' ) )AND(( (node.status = '1') AND (node.type IN  ('_product_and_coupon')) )))"
    );
    $obj = $query->fetch();
    return $obj->total;
  
  }elseif( !empty($brand) ){
  
      $query = db_query("SELECT count(node.nid) as total
      FROM 
      node node
      LEFT JOIN field_data_field_brand field_data_field_brand ON node.nid = field_data_field_brand.entity_id AND (field_data_field_brand.entity_type = 'node' AND field_data_field_brand.deleted = '0')
      LEFT JOIN field_data_field_retailer field_data_field_retailer ON node.nid = field_data_field_retailer.entity_id AND (field_data_field_retailer.entity_type = 'node' AND field_data_field_retailer.deleted = '0')
      WHERE (( (field_data_field_brand.field_brand_tid = '$brand' ) )AND(( (node.status = '1') AND (node.type IN  ('_product_and_coupon')) )))"
    );
    
    $obj = $query->fetch();
    return $obj->total;
      
  }elseif( !empty($retailer) ){
    
    $query = db_query("SELECT count(node.nid) as total
      FROM 
      {node} node
      LEFT JOIN {field_data_field_brand} field_data_field_brand ON node.nid = field_data_field_brand.entity_id AND (field_data_field_brand.entity_type = 'node' AND field_data_field_brand.deleted = '0')
      LEFT JOIN {field_data_field_retailer} field_data_field_retailer ON node.nid = field_data_field_retailer.entity_id AND (field_data_field_retailer.entity_type = 'node' AND field_data_field_retailer.deleted = '0')
      WHERE (( (field_data_field_retailer.field_retailer_tid = '$retailer' ) )AND(( (node.status = '1') AND (node.type IN  ('_product_and_coupon')) )))"
    );
    $obj = $query->fetch();
    return $obj->total;
  }
}

function override_apache_get_Ptotal( $Ptid, $brandId ){
  
  $taxonomyID = array();
  
  $QGetCategoryP = db_query("SELECT d.name, d.tid FROM taxonomy_term_data d INNER JOIN  taxonomy_term_hierarchy h ON d.tid = h.tid WHERE d.vid = 3 and d.tid = '$Ptid' ");
  while( $RGetCategoryP = $QGetCategoryP->fetchObject() ){
    $TermId = $RGetCategoryP->tid;
    $taxonomyID[] = "'".$TermId."'";
    
    
    
    $QGetCategoryChild = db_query("SELECT d.name, d.tid
    FROM taxonomy_term_data d INNER JOIN  taxonomy_term_hierarchy h ON d.tid = h.tid
    WHERE d.vid = 3 and  h.parent = $TermId ");
    
    while( $RGetCategoryChild = $QGetCategoryChild->fetchObject() ){
      $CategoryChildID = $RGetCategoryChild->tid;
      $taxonomyID[] = "'".$CategoryChildID."'";
      
      $QGetCategorySChild = db_query("SELECT d.name, d.tid
      FROM taxonomy_term_data d INNER JOIN  taxonomy_term_hierarchy h ON d.tid = h.tid
      WHERE d.vid = 3 and  h.parent = $CategoryChildID ");
      
      while( $RGetCategorySChild = $QGetCategorySChild->fetchObject() ){
        $taxonomyID[] = "'".$RGetCategorySChild->tid."'";
      }  
    }
  }
  
  $termID = implode(',' , $taxonomyID);
  
  
  $QTotal = db_query("SELECT count(node.nid) as total
  FROM 
  node node
  LEFT JOIN field_data_field_brand field_data_field_brand ON node.nid = field_data_field_brand.entity_id AND (field_data_field_brand.entity_type = 'node' AND field_data_field_brand.deleted = '0')
  LEFT JOIN field_data_field_category field_data_field_category ON node.nid = field_data_field_category.entity_id AND (field_data_field_category.entity_type = 'node' AND field_data_field_category.deleted = '0')
  WHERE (( (field_data_field_category.field_category_tid IN ($termID) ) AND field_data_field_brand.field_brand_tid = '$brandId' )AND(( (node.status = '1') AND (node.type IN  ('_product_and_coupon')) )))");
  
  $RTotal  = $QTotal->fetchObject();
  if( $RTotal->total > 0 )
   // mail('sanjay.kumar1@mail.vinove.com', 'termID', 'termID222-->'.print_r($RTotal,1));
  
  return $RTotal->total;
}

function override_apache_get_sub_sub_cate_total( $Ptid, $brandId ){
  
  $taxonomyID = array();
  
  $QGetCategoryP = db_query("SELECT d.name, d.tid FROM taxonomy_term_data d INNER JOIN  taxonomy_term_hierarchy h ON d.tid = h.tid WHERE d.vid = 3 and d.tid = '$Ptid' ");
  while( $RGetCategoryP = $QGetCategoryP->fetchObject() ){

    $TermId = $RGetCategoryP->tid;
    $taxonomyID[] = "'".$TermId."'";
    
  }
  
  $termID = implode(',' , $taxonomyID);
  
  
  $QTotal = db_query("SELECT count(node.nid) as total
  FROM 
  node node
  LEFT JOIN field_data_field_brand field_data_field_brand ON node.nid = field_data_field_brand.entity_id AND (field_data_field_brand.entity_type = 'node' AND field_data_field_brand.deleted = '0')
  LEFT JOIN field_data_field_category field_data_field_category ON node.nid = field_data_field_category.entity_id AND (field_data_field_category.entity_type = 'node' AND field_data_field_category.deleted = '0')
  WHERE (( (field_data_field_category.field_category_tid IN ($termID) ) AND field_data_field_brand.field_brand_tid = '$brandId' )AND(( (node.status = '1') AND (node.type IN  ('_product_and_coupon')) )))");
  
  $RTotal  = $QTotal->fetchObject();
  if( $RTotal->total > 0 )
    //mail('sanjay.kumar1@mail.vinove.com', 'termID', 'termID222-->'.print_r($RTotal,1));
  
  return $RTotal->total;
}


function override_apache_get_Ctotal($pid, $tid){

  $taxonomyID = array();
  
  $QGetCategoryP = db_query("SELECT d.name, d.tid FROM taxonomy_term_data d INNER JOIN  taxonomy_term_hierarchy h ON d.tid = h.tid WHERE d.vid = 3 and d.tid = $tid and  h.parent = $pid ");
  while( $RGetCategoryP = $QGetCategoryP->fetchObject() ){
    $TermId = $RGetCategoryP->tid;
    $taxonomyID[] = "'".$TermId."'";
    
    $QGetCategoryChild = db_query("SELECT d.name, d.tid
    FROM taxonomy_term_data d INNER JOIN  taxonomy_term_hierarchy h ON d.tid = h.tid
    WHERE d.vid = 3 and  h.parent = $TermId ");
    
    while( $RGetCategoryChild = $QGetCategoryChild->fetchObject() ){
      $CategoryChildID = $RGetCategoryChild->tid;
      $taxonomyID[] = "'".$CategoryChildID."'";
      
      $QGetCategorySChild = db_query("SELECT d.name, d.tid
      FROM taxonomy_term_data d INNER JOIN  taxonomy_term_hierarchy h ON d.tid = h.tid
      WHERE d.vid = 3 and  h.parent = $CategoryChildID ");
      
      while( $RGetCategorySChild = $QGetCategorySChild->fetchObject() ){
        $taxonomyID[] = "'".$RGetCategorySChild->tid."'";
      }  
    }
  }
  
  $termID = implode(',' , $taxonomyID);  
  return $termID;
}

//get combination of url retailer and category
function override_apache_get_RCURL($pid, $tid){
  $taxonomyID = array();
  
  //echo "SELECT d.name, d.tid FROM taxonomy_term_data d INNER JOIN  taxonomy_term_hierarchy h ON d.tid = h.tid WHERE d.vid = 2 and d.tid = $tid ";
  $QGetCategoryP = db_query("SELECT d.name, d.tid FROM taxonomy_term_data d INNER JOIN  taxonomy_term_hierarchy h ON d.tid = h.tid WHERE d.vid = 2 and d.tid = $tid ");
  while( $RGetCategoryP = $QGetCategoryP->fetchObject() ){
    $TermId = $RGetCategoryP->tid;
    $taxonomyID[] = "'".$TermId."'";
    
    $QGetCategoryChild = db_query("SELECT d.name, d.tid
    FROM taxonomy_term_data d INNER JOIN  taxonomy_term_hierarchy h ON d.tid = h.tid
    WHERE d.vid = 3 and  h.parent = 0 ");
    
    while( $RGetCategoryChild = $QGetCategoryChild->fetchObject() ){
      $CategoryChildID = $RGetCategoryChild->tid;
      $taxonomyID[] = "'".$CategoryChildID."'";
      
      $QGetCategorySChild = db_query("SELECT d.name, d.tid
      FROM taxonomy_term_data d INNER JOIN  taxonomy_term_hierarchy h ON d.tid = h.tid
      WHERE d.vid = 3 and  h.parent = $CategoryChildID ");
      
      while( $RGetCategorySChild = $QGetCategorySChild->fetchObject() ){
        $taxonomyID[] = "'".$RGetCategorySChild->tid."'";
      }  
    }
  }
  
  $termID = implode(',' , $taxonomyID);
  
  $QTotal = db_query("SELECT count(node.nid) as total
  FROM 
  node node
  LEFT JOIN field_data_field_retailer field_data_field_retailer ON node.nid = field_data_field_retailer.entity_id AND (field_data_field_retailer.entity_type = 'node' AND field_data_field_retailer.deleted = '0')
  LEFT JOIN field_data_field_category field_data_field_category ON node.nid = field_data_field_category.entity_id AND (field_data_field_category.entity_type = 'node' AND field_data_field_category.deleted = '0')
  WHERE (( (field_data_field_category.field_category_tid IN ($termID) ) AND field_data_field_retailer.field_retailer_tid = '$tid' )AND(( (node.status = '1') AND (node.type IN  ('_product_and_coupon')) )))");
  
  $RTotal  = $QTotal->fetchObject();
  
  return $RTotal->total;
}


function override_apache_get_RCPtotal( $Ptid, $brandId ){

  $taxonomyID = array();
  
  $QGetCategoryP = db_query("SELECT d.name, d.tid FROM taxonomy_term_data d INNER JOIN  taxonomy_term_hierarchy h ON d.tid = h.tid WHERE d.vid = 3 and d.tid = '$Ptid' ");
  while( $RGetCategoryP = $QGetCategoryP->fetchObject() ){
    $TermId = $RGetCategoryP->tid;
    $taxonomyID[] = "'".$TermId."'";
    
    $QGetCategoryChild = db_query("SELECT d.name, d.tid
    FROM taxonomy_term_data d INNER JOIN  taxonomy_term_hierarchy h ON d.tid = h.tid
    WHERE d.vid = 3 and  h.parent = $TermId ");
    
    while( $RGetCategoryChild = $QGetCategoryChild->fetchObject() ){
      $CategoryChildID = $RGetCategoryChild->tid;
      $taxonomyID[] = "'".$CategoryChildID."'";
      
      $QGetCategorySChild = db_query("SELECT d.name, d.tid
      FROM taxonomy_term_data d INNER JOIN  taxonomy_term_hierarchy h ON d.tid = h.tid
      WHERE d.vid = 3 and  h.parent = $CategoryChildID ");
      
      while( $RGetCategorySChild = $QGetCategorySChild->fetchObject() ){
        $taxonomyID[] = "'".$RGetCategorySChild->tid."'";
      }  
    }
  }
  
  $termID = implode(',' , $taxonomyID);
  
  $QTotal = db_query("SELECT count(node.nid) as total
  FROM 
  node node
  LEFT JOIN field_data_field_retailer field_data_field_retailer ON node.nid = field_data_field_retailer.entity_id AND (field_data_field_retailer.entity_type = 'node' AND field_data_field_retailer.deleted = '0')
  LEFT JOIN field_data_field_category field_data_field_category ON node.nid = field_data_field_category.entity_id AND (field_data_field_category.entity_type = 'node' AND field_data_field_category.deleted = '0')
  WHERE (( (field_data_field_category.field_category_tid IN ($termID) ) AND field_data_field_retailer.field_retailer_tid = '$brandId' )AND(( (node.status = '1') AND (node.type IN  ('_product_and_coupon')) )))");
  
  $RTotal  = $QTotal->fetchObject();
  
  return $RTotal->total;
}

function override_apache_modify_title($title){
  
  $string = $title;
  $string = str_replace('.', '', $string);
  $str = preg_replace('/[^A-Za-z0-9\-]/', '-', $string);
  $str = trim( preg_replace('/-{1,}/','-',$str), '-' );
  return $str;  

}  