<?php

function coupons_menu() {
  $items = array();

  $items['coupon-finder'] = array( //this creates a URL that will call this form at "examples/form-example"
      'title' => 'Coupon Finder', //page title
      'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
      'page arguments' => array('coupons_finder_form'), //put the name of the form here
      'access callback' => TRUE
  );

  $items['coupon-result/%'] = array(
      'title' => t(''),
      'page callback' => 'coupons_result',
      'page arguments' => array(1),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
  );

  $items['coupon-redirect'] = array(
      'page callback' => 'coupons_redirect_interim_page',
      'page arguments' => array(),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
  );


  return $items;
}

function coupons_redirect_interim_page() {
  $url = $_GET['s'];
  $coupon_code = $_GET['c'];
  $url = urldecode($url);
  drupal_add_js("jQuery(window).load(function($){
           setTimeout(function(){
              window.location.replace(\"".$url."\");
          }, 3000);
        });",
      array('type' => 'inline', 'scope' => 'footer'));

  return '<div class="coupon_window">
            <h1>Thank you for visiting our site</h1>
            <h2>We are forwarding you to our retailer</h2>
            <div class="clear"> </div>
            <div class="coupon_window_title">
              Your coupon code is:<div class="bridgecode">'.$coupon_code.'</div>
            </div>
            <div class="clear"> </div>
            <div class="coupon_window_redirect">
              Been waiting a while? Go directly to&nbsp;
              <a rel="nofollow" href="'.$url.'"><b>Click here</b>
              </a>
            </div>
            <div class="clear"> </div>
          </div>';
}


/**
 * Implementation of hook_menu
 */
function coupons_theme() {
  $themes = array(
      'coupons_result_page' => array(
          'template' => 'coupon-finder-search-page',
          'variables' => array('data' => null),
      ),
  );

  return $themes;
}


function coupons_finder_form($form, &$form_state, $small = true) {
  $form['url'] = array(
      '#title'=>t('Try Another Product'),
      '#type' => 'textfield',
      '#size' => 100,
      '#default'=>t('Enter URL of the Product Page'),
      '#maxlength' => 255,
  );

  $form['actions']['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Find My Coupons'),
  );

  if ($small) {
    $form['url']['#title'] = t('Know what you want to buy? Just enter the url of the product page and let coupons find you:');
    $form['url']['#description'] = t('e.g. http://www.jabong.com/giordano-P6868-Black-Analog-Watch-183702.html');
    $form['actions']['view_video'] = array(
        '#markup' => l('View Demo','test'),
    );
  }
  return $form;
}

function coupons_finder_form_validate($form, &$form_state) {
  if (($form_state['values']['url'] == "")) {
    form_set_error('URL', t('URL shouldn\'t be empty.'));
  }
}

function coupons_finder_form_submit($form, &$form_state) {
  $form_state['redirect'] = 'coupon-result/'.urlencode($form_state['values']['url']);
}

function coupons_result($url) {
  $url = "http://plugin.theshoppingpro.com/CouponAutoWeb.php?q=".urldecode($url);
  $json = file_get_contents($url);
  $jsonData = preg_replace("/[\\n\\r]+/", " ", $json);
  $jsonArray = json_decode($jsonData);
  $output = '';
  if(isset($jsonArray)) {
    $title = t('Results for:'.urldecode($url));
    $items = array();
    $type = 'ul';
    $attributes = array(
        'id' => 'coupon_search_listing',
        'class' => 'custom-coupon_search_listing',
    );
    $i = 0;
    $coupons = array();
    foreach ($jsonArray as $key => $value) {
      if (is_object($value)) {
        $i++;
        $value->counter=$i;
        $items[] = array(
            'data' => theme('coupons_result_page',array('row'=>$value)),
            'id' => 'search_listing_li_row_'.$i,
            'class' => array('search_listing_row_li'),
        );
        $coupons['c_'.$i] = $value->couponCode;
      }
    }
    drupal_add_js(array('coupons' => $coupons), 'setting');
    drupal_add_js("jQuery(document).ready(function($){
          $('.unlock_coupon').click(function(){
              var coupon_code = Drupal.settings.coupons.c_1;
              $(this).html(Drupal.settings.coupons.c_1);
              var url = $(this).attr('href')+'&c='+coupon_code;
              $(this).attr('href',url);
              return true;
          });
        });",
        array('type' => 'inline', 'scope' => 'footer'));
    return theme_item_list(array('items' => $items, 'title' => $title, 'type' => $type, 'attributes' => $attributes));
  }
}



/**
 * Implementation of hook_theme
 */
/**
 * Implements hook_block_info().
 */
function coupons_block_info() {
  $blocks['coupons_block_form'] = array(
      'info' => t('Coupon finder block.'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * Prepares the contents of the block.
 */
function coupons_block_view($delta = '') {
  $block = array();
  switch($delta) {
    case 'coupons_block_form':
      $block['content'] = drupal_get_form('coupons_finder_form',false);
      break;

  }
  return $block;
}