<?php
/* CREATING AN API FOR UPDATE OF RETAILER COUPON NODES*/
function retailer_coupon_menu() {
  $items = array();
  $items['add-coupon/%'] = array(//this creates a URL that will call this form at "examples/form-example"
      'title' => 'Add Coupons in database', //page title
      'page callback' => 'retailer_coupon_addcoupon', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
      'page arguments' => array(1),
      'access callback' => TRUE
  ); 

  return $items;
}


/* FUNCTION THAT THE RETAILER API CALLS TO CREATE / UPDATE  REATILER COUPON*/
function retailer_coupon_addcoupon($CouponInfo){
$retailer = reset(explode('_',$_REQUEST['retailer']));
//$retailer = reset(explode('_',$urlParam));
	$url = "http://54.243.150.171/cpnVodo/nodecreation/cpnPageNodeCreation.php?retailer=".$retailer; //The API TO GET ALL RETAILER COUPON DATA 
	$json = drupal_http_request($url, array('timeout' => 600.0));
   	$json = $json->data;
    $jsonArr = json_decode($json,true);
	echo 'Array Size ------->'.sizeof($jsonArr);
	// LOOP TO PROCESS EACH RETAILER COUPON RECORD RECEIVED VIA THE API
	foreach($jsonArr as $json){ 
		$json = json_encode($json); 
    	$jsonData = preg_replace("/[\\n\\r]+/", " ", $json);
    	$jsonArray = json_decode($jsonData);
		// var_dump($json);
    	// ASSIGN ALL COUPON DATA TO VARIABLES
		$couponInfo = $jsonArray->couponInfo;
		$baseUrl= trim($couponInfo->BaseUrl);
    	$retailer = trim($couponInfo->Retailer);
    	$retailerId = trim($couponInfo->RetailerId);
    	$afiliateUrl = trim($couponInfo->AfiliateUrl);
    	$lastCheckedTime = trim($couponInfo->LastCheckedTime);
    	$couponCode = trim($couponInfo->CouponCode);
    	$couponTitle = trim($couponInfo->CouponTitle);
    	$couponCodeDesc = trim($couponInfo->CouponCodeDesc);
    	$offerType = trim($couponInfo->OfferType);
    	$status = trim($couponInfo->Status);
    	$weight = trim($couponInfo->weight);
		//CHECK IF NODE EXISTS (INCASE OF COUPONS CHECK VIA COUPON CODE AND RETAILER ID ELSE VIA COUPON TITLE AND RETAILER ID
		//echo "offer type: ".$offerType;
		if ($offerType == 14702){
		$query = new EntityFieldQuery();
		$query->entityCondition('entity_type', 'node')
		->entityCondition('bundle', 'retailer_coupon_page')
		->fieldCondition('field_retailer', 'tid', $retailerId, '=')
		->fieldCondition('field_coupon_code', 'value', $couponCode, '=');
		// ->fieldCondition('field_coupon_title', 'value', $couponTitle, '='); // ENSURING COUPON IS UNIQUE THIS MEANS THAT LAST INSTANCE OF THE COUPON WILL GO LIVE - RECHECK IF THATS OK
		}
		else {
		$query = new EntityFieldQuery();
		$query->entityCondition('entity_type', 'node')
		->entityCondition('bundle', 'retailer_coupon_page')
		->fieldCondition('field_retailer', 'tid', $retailerId, '=')
		//->fieldCondition('field_coupon_code', 'value', $couponCode, '='); // FOR DEALS WE ARE USING TITLE AS UNIQUE IDENTIFIER
		 ->fieldCondition('field_coupon_title', 'value', $couponTitle, '='); 
		}
		$result = $query->execute();
		$nids = array_keys($result['node']);
		 var_dump($nids); //COMMENT THIS POST TEXTING
		// echo $nids[0]; // COMMENT THIS POST TESTING
	  
	  
    	if (empty($result['node'])) {
			// CREATING NODE SINCE IT DOES NOT EXIST	
			$node = new stdClass();
			echo 'inside new';			
	        $node->language = 'und';
			$node->type     = 'retailer_coupon_page';
			$node->uid      = 1; 
		}
		else {
			// LOADING THE IDENTIFIED NODE & DELETING ALL CATEGORY LINK VALUES
			echo 'inside update';
			var_dump($nids[0]);
			$node = node_load($nids[0]);
			unset($node->field_category_links_multi);
		}
		// COMMON PROCESS FOR UPDATE AND NEW NODE SINCE NODE IS NOW IDENTIFIED / CREATED
		// PUSHING IN MAIN DATA (I.E. ALL EXCEPT CATEGORY LINKS) 
		$node->title = $couponTitle.' @ '.ucfirst($retailer);
		$node->body = $couponTitle.' @ '.$retailer;
		$node->field_baseurl_coupon['und']['0']['value']			= $baseUrl;
		$node->field_retailer['und'][0][tid]			= $retailerId;
		$node->field_coupon_code['und']['0']['value']			= $couponCode;
		$node->field_offer_type['und'][0][tid]			= $offerType;
		$node->field_coupon_title['und']['0']['value']			= $couponTitle;
		$node->field_field_coupon_expiry['und']['0']['value']			= $lastCheckedTime;
		$node->field_coupon_description['und']['0']['value']			= $couponCodeDesc;
		$node->field_affiliate_url['und']['0']['value']			= $afiliateUrl;
		$node->field_weight['und']['0']['value']			= $weight;
		$node->field_status['und']['0']['value']			= $status;
		$node->field_affiliate_url['und']['0']['value']			= $afiliateUrl;
		// PUSHING IN CATEGORY LINKS 
			$categoryLinksArr = $jsonArray->CategoryLinks;
    		if ($categoryLinksArr != null){
			//echo 'inside loop'; // COMMENT POST TESTING
			 $c=0; // COMMENT POST TESTING
				//RUNNING LOOP FOR EACH CATEGORY LINK SET 
				foreach($categoryLinksArr as $categoryLinks){
    				$c=$c+1; // COMMENT POST TESTING
				//	echo 'loop'.$c; // COMMENT POST TESTING
				//	echo nl2br("\n"); // COMMENT POST TESTING
				//	var_dump($categoryLinks); // COMMENT POST TESTING
					$categoryId = $categoryLinks->CategoryId;
					$affiliateUrl = $categoryLinks->AffiliateUrl;
					$fc_item = entity_create('field_collection_item', array('field_name' => 'field_category_links_multi'));
					$fc_item->setHostEntity('node', $node);
					$fc_wrapper = entity_metadata_wrapper('field_collection_item', $fc_item);
					$fc_wrapper->field_link_retailer_id_multi->set($retailerId);
					$fc_wrapper->field_link_affiliate_url_multi->set($affiliateUrl);
					$fc_wrapper->field_link_coupon_code_multi->set($couponCode);
					$fc_wrapper->field_link_coupon_desc_multi->set($couponCodeDesc);
					$fc_wrapper->field_link_category_id_multi->set($categoryId);
					$fc_wrapper->save(true);
					
     				}
    		} 
		node_save($node);
		echo 'node saved';
    }
echo 'No node to process';
}

function retailer_coupon_cron(){
mail('team@theshoppingpro.com','test-run','test');
	$run = 1;
	$i = 0;
	$Query = db_select('1Variables', 'b')
				 ->fields('b', array('Status') )
				 ->condition('b.Variable', 'Updat_PredictorCompiledResultTableDmp_Table', '=');
	$run_check = $Query->execute();
	$run_check_fetch = $run_check->fetch();
	$isFirstRun = $run_check_fetch->Status;
	
	mail('team@theshoppingpro.com','test-run', $isFirstRun);
	
    echo $isFirstRun;
	If ($isFirstRun == 1) {
		db_query("Truncate table coupon_finder.predictorCompiledResultTableDmp");
		db_query("insert into coupon_finder.predictorCompiledResultTableDmp select * from coupon_finder.predictorCompiledResultTable");
		db_query("Truncate table coupon_finder.predictorCompiledResultTable");
		db_query("UPDATE coupon_finder.1Variables SET Status = 2, Ref_Value = '".gmdate('Y-m-d\TH:i:s\Z', time())."' WHERE Variable = 'Updat_PredictorCompiledResultTableDmp_Table'");
	}

	
	If ($isFirstRun == 2) {
		return 'dont run';
		exit;
	}
	
	while ($run ==1) {
		$i++;
		$url = "http://54.243.150.171/cpnVodo/SimulationWithoutAutomatn/pustToMySql.php"; //The API TO GET ALL RETAILER COUPON DATA 
		$json = drupal_http_request($url, array('timeout' => 1200.0));
		//var_dump($json);
		$json = $json->data;
		if ($json != 'null') {
			if ($i == 1) {mail('team@theshoppingpro.com', 'Data Push Start', gmdate('Y-m-d\TH:i:s\Z', (time()+(5.5*3600))));}
			$jsonArr = json_decode($json,true);
			foreach($jsonArr as $json){ 
				$json = json_encode($json); 
				$jsonData = preg_replace("/[\\n\\r]+/", " ", $json);
				$jsonArray = json_decode($jsonData);
			
				$id= trim($jsonArray->id);
				$baseUrl= trim($jsonArray->BaseUrl);
				$listPrice= trim($jsonArray->listPrice);
				$MRP= trim($jsonArray->MRP);
				$Saving= trim($jsonArray->Saving);
				$NetPrice= trim($jsonArray->NetPrice);
				$BestCouponCode= trim($jsonArray->BestCouponCode);
				$BestCouponDesc= trim($jsonArray->BestCouponDesc);
				$result= trim($jsonArray->result);
				$entity_id= null;
				$brand= trim($jsonArray->brand);
				$ProductName= trim($jsonArray->ProductName);
				$ProductImage= trim($jsonArray->ProductImage);
				$Category= trim($jsonArray->Category);
				$LastCheckTime= trim($jsonArray->LastCheckTime);
				$pagetitle= trim($jsonArray->pagetitle);
				$BestCouponStatus= trim($jsonArray->BestCouponStatus);
				$BrandId= null;
				$loc= null;
				$retailer= trim($jsonArray->retailer);
				$retailerId= trim($jsonArray->retailerId);
				$bestCouponDisplay= trim($jsonArray->bestCouponDisplay);
				
				$nid = db_insert('predictorCompiledResultTable') // Table name no longer needs {}
				->fields(array(
				  'id' => $id,
				  'BaseUrl' => $baseUrl,
				  'ListPrice' => $listPrice,
				  'MRP' => $MRP,
				  'Saving' => $Saving,
				  'NetPrice' => $NetPrice,
				  'BestCouponCode' => $BestCouponCode,
				  'BestCouponDesc' => $BestCouponDesc,
				  'Result' => $result,
				  'entity_id' => $entity_id,
				  'Brand' => $brand,
				  'ProductName' => $ProductName,
				  'ProductImage' => $ProductImage,
				  'Category' => $Category,
				  'LastCheckTime' => $LastCheckTime,
				  'pagetitle' => $pagetitle,
				  'BestCouponStatus' => $BestCouponStatus,
				  'BrandId' => $BrandId,
				  'loc' => $loc,
				  'Retailer' => $retailer,
				  'RetailerId' => $retailerId,
				  'BestCouponDisplay' => $bestCouponDisplay,
				))
				->execute();
				
			}
		} Else {
			// no urls to process
			$run = 0;
			if($i!=1) {
				mail('team@theshoppingpro.com', 'Data Push Ended With '.$i.' loops', gmdate('Y-m-d\TH:i:s\Z', (time()+(5.5*3600))));
				db_query("UPDATE coupon_finder.1Variables SET Status = 1, Ref_Value = '".gmdate('Y-m-d\TH:i:s\Z', time())."' WHERE Serial = 1");
				db_query("UPDATE coupon_finder.1Variables SET Status = 3, Ref_Value = '".gmdate('Y-m-d\TH:i:s\Z', time())."' WHERE Variable = 'Updat_PredictorCompiledResultTableDmp_Table'");
			} else {
				mail('team@theshoppingpro.com', 'Data Push Did Not Run', gmdate('Y-m-d\TH:i:s\Z', (time()+(5.5*3600))));
			}
		}
	}
}