<?php

function retiler_coupon_menu() {
  $items = array();

  $items['add-coupon/%'] = array(//this creates a URL that will call this form at "examples/form-example"
      'title' => 'Add Coupons in database', //page title
      'page callback' => 'retiler_coupon_addcoupon', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
      'page arguments' => array(1),
      'access callback' => TRUE
  );

  return $items;
}

function retiler_coupon_addcoupon($ProInfo){
	
$url = "http://54.243.150.171/test/test3.php";
	
    $json = drupal_http_request($url, array('timeout' => 600.0));
   	
	
	
    $json = $json->data;
   
    
    $jsonArr = json_decode($json,true);
    foreach($jsonArr as $json){
     
     
     	$json = json_encode($json); 
    	$jsonData = preg_replace("/[\\n\\r]+/", " ", $json);
    	$jsonArray = json_decode($jsonData);
    	$couponInfo = $jsonArray->couponInfo;
    	$retailer = trim($couponInfo->Retailer);
    	$retailerId = trim($couponInfo->RetailerId);
    	$afiliateUrl = trim($couponInfo->AfiliateUrl);
    	$lastCheckedTime = trim($couponInfo->LastCheckedTime);
    	$couponCode = trim($couponInfo->CouponCode);
    	$couponTitle = trim($couponInfo->CouponTitle);
    	$couponCodeDesc = trim($couponInfo->CouponCodeDesc);
    	$offerType = trim($couponInfo->OfferType);
    	$status = trim($couponInfo->Status);
    	$weight = trim($couponInfo->weight);
    	//To Chnge db Query to check if the node exists
    	$query = new EntityFieldQuery();
	$query->entityCondition('entity_type', 'node')
	  ->entityCondition('bundle', 'retailer_coupon')
	  ->fieldCondition('field_retailer', 'value', $retailer, '=')
	  ->fieldCondition('field_coupon_code', 'value', $couponCode, '=')
	  ->fieldCondition('field_coupon_title', 'value', $couponTitle, '=');
	  $result = $query->execute();
    	if (empty($result['node'])) {
	echo 'add';
	die;
	        $node = new stdClass();
	        $node->language = LANGUAGE_NONE;
		$node->type     = '_product_and_coupon';	// change
		$node->uid      = 1; // change
		$node->field_coupon_code['und']['0']['value']			= $retailer;
		$node->field_offer_type['und'][0][tid]			= $offerType;
		$node->field_coupon_title['und']['0']['value']			= $couponTitle;
		$node->field_coupon_expiry['und']['0']['value']			= $lastCheckedTime;
		$node->field_coupon_description['und']['0']['value']			= $couponCodeDesc;
		$node->field_affiliate_url['und']['0']['value']			= $afiliateUrl;
		$node->field_weight['und']['0']['value']			= $weight;
		$node->field_status['und']['0']['value']			= $status;
		$node->field_affiliate_url['und']['0']['value']			= $afiliateUrl;
		
		 
		 
    		$categoryLinks = $jsonArray->CategoryLinks;
    		if ($categoryLinks != null){
    			$categoryLinksArr = json_decode($categoryLinks,true);
    			foreach($categoryLinksArr as $categoryLinks){
    				$categoryId = $categoryLinks->CategoryId;
    				$affiliateUrl = $categoryLinks->AffiliateUrl;
     				}
    		} 
    	}else { 
    	//echo 'update';
    	$node = node_load($record->entity_id);
    	
    	
    	}
    }
    
    }
?> 
