<?php

/**
* Implements hook_permission().
*/
function partner_program_permission() {
return array(
'access partner program script' => array(
'title' => t('Access the partner program script'),
),

);
}

/**
* Implementation of hook_menu
*/
function partner_program_menu() {
$items['partner_program'] = array(
'title' => 'Partner Program Information',
'description' => 'TheShoppingPro - Partner Program',
'page callback' => 'partner_program_script',
'type' => MENU_CALLBACK,
'access arguments' => array('access partner program script'),
);

return $items;
}


/**
 * Implementation of hook_theme
 */
function partner_program_theme() {
  $themes = array(
      'partner_program_script_page' => array(
          'template' => 'partner-program-script-page',
          'variables' => array('data' => null),
      ),
  );

  return $themes;
}

function partner_program_script() {
  global $user, $base_url;
  $referrerid=_referral_uid2ref($user->uid);

   drupal_add_js(drupal_get_path('module', 'partner_program') .'/zeroclipboard.js');

/*
   drupal_add_js((drupal_get_path('module', 'partner_program') .'/shoppingpro.js'), 
 array('type' => 'file', 'scope' => 'footer', 'weight' => 5)
  );
 
 $link = $base_url."/referral/" . _referral_uid2ref($user->uid);
*/
  $data = array(
      'referrerid' => $referrerid,
  );
  

  return theme('partner_program_script_page', array('data' => $data));

}




/**
* Implements hook_block_info().
*/
function partner_program_block_info() {
  $blocks['current_posts'] = array(
    'info' => t('Partner Program Script'), //The name that will appear in the block list.
    'cache' => DRUPAL_CACHE_PER_ROLE, //Default
  );
  return $blocks;
}

/**
* Implements hook_block_view().
*
* Prepares the contents of the block.
*/
function partner_program_block_view($delta = '') {
  switch($delta){
    case 'current_posts':
      $block['subject'] = t('');
	  $block['content'] = partner_program_script();
    return $block;
  }
 
}