<?php


function custom_sort_apachesolr_query_prepare(&$query){
    
    $query->setAvailableSort('its_field_product_popularity', array('title' => t('Popularity'), 'default' => 'asc'));
    $query->setAvailableSort('its_field_best_coupon_netpriceaf', array('title' => t('Net Price'), 'default' => 'asc'));
    $query->setAvailableSort('its_field_product_price', array('title' => t('Listing Price'), 'default' => 'asc'));
    $query->setAvailableSort('its_field_best_coupon_saving', array('title' => t('Savings'), 'default' => 'asc'));
    
    $query->removeAvailableSort('ds_created');
    $query->removeAvailableSort('sort_label');
    $query->removeAvailableSort('bundle');
    $query->removeAvailableSort('sort_name');
 
}

/**
 * Implements hook_apachesolr_process_results
 */
function custom_sort_apachesolr_process_results(array &$results, DrupalSolrQueryInterface $query) {
    drupal_add_js("jQuery(window).load(function() {
        ga('send', 'event', 'site-search', 'keyword', Drupal.settings.ga_search.keyword,{'dimension6': Drupal.settings.ga_search.current_page});
        });", array('type' => 'inline', 'scope' => 'footer'));
}
