<?php

include_once 'includes/mixpanel_defaults.node.inc';
include_once 'includes/mixpanel_defaults.user.inc';
include_once 'includes/mixpanel_defaults.comment.inc';
include_once 'includes/mixpanel_defaults.og.inc';

/**
 * Implements hook_init().
 */
function mixpanel_defaults_init() {
  // Track visits to user pages.
  if (arg(0) == "user" && is_numeric(arg(1))) {
    mixpanel_track("user-view-profile", array('visited-user' => arg(1)));
  }
}

/**
 * Implements hook_form_alter().
 */
function mixpanel_defaults_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'contact_personal_form':
      $form['#submit'][] = "mixpanel_defaults_contact_personal_form_submit";
      break;
    case 'user_profile_form':
      $form['#submit'][] = "mixpanel_defaults_user_profile_form_submit";
      break;
    case 'search_form':
    case 'search_block_form':
      $form['#submit'][] = "mixpanel_defaults_search_form_submit";
      break;
  }
}

