<?php
define("CORP_RETAILERS_CATEGORY_VID", 3);
define("CORP_RETAILERS_MEGASTORE_TID", 29);
define("CORP_RETAILERS_PARTNER_TID", 13);
define("CORP_RETAILERS_COMPETITOR_TID", 14);

/**
 * Implementation of hook_menu
 */
function corp_retailers_menu() {
  $items['retailers-partners-list1'] = array(
      'title' => 'TheShoppingPro',
      'description' => 'TheShoppingPro - retailers partner list',
      'page callback' => 'corp_retailers_list',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
  );
  return $items;
}


/**
 * Implementation of hook_menu
 */
function corp_retailers_theme() {
  $themes = array(
      'corp_retailers_list_page' => array(
          'template' => 'corp-retailers-list-page',
          'variables' =>  array('data' => null),
      ),
  );

  return $themes;
}

function corp_retailers_list() {
  $redirect = $_GET['redirect'];
  $url = strtolower($_GET['url']);
  $uid2 = $_GET['uid2'];

  // categories
  $category = taxonomy_get_tree(CORP_RETAILERS_CATEGORY_VID);
  foreach($category  as $cat) {
    $categories[$cat->tid] = $cat->name;
  }




  $url = strtolower($url);

  $node = corp_retailers_get_matching($url);


  $node_type = '';
  if ($node->field_type_tid == CORP_RETAILERS_PARTNER_TID) {
    $node_type  = 'partner';
  }elseif($node->field_type_tid == CORP_RETAILERS_COMPETITOR_TID) {
    $node_type  = 'competitor';
  }else {
    if ($node->nid) {
      $node_type  = 'sites_of_interest';
    }else {
      $node_type  = 'notfound';
    }
  }

  $output  = array();
  if ($node->nid) {
    $output = array('partners'=> array(0=> $node));
  }


  $matching_node = array(
      'url' => isset($node->field_url_value) ? $node->field_url_value : $node->field_url_site_of_interest_value,
      'nid'=> $node->nid,
      'type'=> ($node->field_type_tid == CORP_RETAILERS_PARTNER_TID) ?  $node->field_type_tid : CORP_RETAILERS_COMPETITOR_TID,
      'country'=> isset($node->field_country_tid) ? explode(",", $node->field_country_tid) : 4,
      'category'=> ($node->field_type_tid == CORP_RETAILERS_PARTNER_TID) ? array_keys($categories) : explode(',', $node->field_category_tid),
  );

  switch ($node_type) {
    case 'partner':
      $output = array_merge($output, corp_retailers_get_mostpopulars($matching_node));
      break;
    case 'competitor':
    case 'sites_of_interest':
      $output = corp_retailers_get_recommended($matching_node);
      $output = array_merge($output, corp_retailers_get_mostpopulars($matching_node));
      break;
    case 'notfound':
      $output = array_merge($output, corp_retailers_get_mostpopulars($matching_node));
      break;
  }

  $data = array(
      'items' => $output,
      'categories' => $matching_node['category'],
      'url' => $url,
      'uid2'=> $uid2,
      'redirect'=>$redirect,
  );
  return theme('corp_retailers_list_page', array('data'=>$data));

}


function corp_retailers_get_recommended($matching_node) {
  $return = array(
      'recommended' => array(
          'popular' => array(),
          'megastore' => array(),
          'rest' => array(),
      ),
  );

  $query = db_select('node','n')
      ->fields('n', array('nid','title'));

  $query->leftJoin('field_data_field_type','fd',"n.nid = fd.entity_id and fd.entity_type='node' AND fd.deleted=0");
  $query->leftJoin('field_data_field_display_text','dt',"n.nid = dt.entity_id and dt.entity_type='node' AND dt.deleted=0");
  $query->leftJoin('field_data_field_image','img',"n.nid = img.entity_id and img.entity_type='node' AND img.deleted=0");
  $query->leftJoin('field_data_field_url_site_of_interest','soi',"n.nid = soi.entity_id and soi.entity_type='node' AND soi.deleted=0");
  $query->leftJoin('field_data_field_country','cntry',"n.nid = cntry.entity_id and cntry.entity_type='node' AND cntry.deleted=0");
  $query->leftJoin('field_data_field_primary_category','prmcat',"n.nid = prmcat.entity_id and prmcat.entity_type='node' AND prmcat.deleted=0");
  $query->leftJoin('field_revision_field_is_popular','pop',"n.nid = pop.entity_id and pop.entity_type='node' AND pop.deleted=0");

  $query->leftJoin('field_data_field_category','cat',"n.nid = cat.entity_id and cat.entity_type='node' AND cat.deleted=0");
  $query->leftJoin('field_data_field_url','url',"n.nid = url.entity_id and url.entity_type='node' AND url.deleted=0");
  $query->leftJoin('weight_weights','weight',"n.nid = weight.entity_id");
  $query->leftJoin('field_data_field_tracking_url','tu',"n.nid = tu.entity_id and tu.entity_type='node' AND tu.deleted=0");
  $query->fields('tu', array('field_tracking_url_value'));
  $query->leftJoin('field_collection_item','fci',"tu.field_tracking_url_value = fci.item_id");

  $query->leftJoin('field_data_field_url_part1','p1',"p1.entity_id = tu.field_tracking_url_value");
  $query->leftJoin('field_data_field_url_part2','p2',"p2.entity_id = tu.field_tracking_url_value");
  $query->leftJoin('field_data_field_url_part3','p3',"p3.entity_id = tu.field_tracking_url_value");
  $query->leftJoin('field_data_field_url_part4','p4',"p4.entity_id = tu.field_tracking_url_value");
  $query->fields('p1', array('field_url_part1_value'));
  $query->fields('p2', array('field_url_part2_value'));
  $query->fields('p3', array('field_url_part3_value'));
  $query->fields('p4', array('field_url_part4_value'));
  $query->fields('url', array('field_url_value'));
  $query->fields('dt', array('field_display_text_value'));
  $query->fields('img', array('field_image_fid'));
  $query->fields('pop', array('field_is_popular_value'));
  $query->fields('soi', array('field_url_site_of_interest_value'));
  $query->addExpression('GROUP_CONCAT(prmcat.field_primary_category_tid)', 'field_primary_category_tid');

  $query->condition('n.status','1');
  $query->condition('n.type', 'retailers', '=');
  $query->condition('n.nid', $matching_node['nid'], '<>');
  $query->condition('fd.field_type_tid', CORP_RETAILERS_PARTNER_TID, '=');

  if (isset($matching_node['category'][0]) && !empty($matching_node['category'][0])) {
#    $query->condition('prmcat.field_primary_category_tid', array_values($matching_node['category']), 'IN');
    $query->condition('cat.field_category_tid', array_values($matching_node['category']), 'IN');
  }
  $query->where('(fd.field_type_tid = :arg OR  fd.field_type_tid IS NULL )', array(':arg'=>CORP_RETAILERS_PARTNER_TID));
  if (isset($matching_node['country'][0]) && !empty($matching_node['country'][0])) {
    $query->condition('cntry.field_country_tid', $matching_node['country'], 'IN');
  }
  $query->orderBy('weight.weight');
  $query->orderBy('url.field_url_value');
  $query->groupBy('n.nid');

  # echo $query;

  $result = $query->execute();
  while($row = $result->fetchObject()) {
    $primary_cat = explode(',', $row->field_primary_category_tid);
    if(in_array(CORP_RETAILERS_MEGASTORE_TID, $primary_cat)) {
      $return['recommended']['megastore'][] = $row;
    }else {
      $return['recommended']['rest'][] = $row;
    }
  }

  $return['recommended'] = array_merge($return['recommended']['megastore'], $return['recommended']['rest']);

  return $return;
}

function corp_retailers_get_mostpopulars($matching_node) {
  $return = array(
      'most_populars' => array(),
  );

  $query = db_select('node','n')
      ->fields('n', array('nid','title'));

  $query->leftJoin('field_data_field_type','fd',"n.nid = fd.entity_id and fd.entity_type='node' AND fd.deleted=0");
  $query->leftJoin('field_data_field_display_text','dt',"n.nid = dt.entity_id and dt.entity_type='node' AND dt.deleted=0");
  $query->leftJoin('field_data_field_image','img',"n.nid = img.entity_id and img.entity_type='node' AND img.deleted=0");
  $query->leftJoin('field_data_field_url_site_of_interest','soi',"n.nid = soi.entity_id and soi.entity_type='node' AND soi.deleted=0");
  $query->leftJoin('field_data_field_country','cntry',"n.nid = cntry.entity_id and cntry.entity_type='node' AND cntry.deleted=0");
  $query->leftJoin('field_data_field_primary_category','prmcat',"n.nid = prmcat.entity_id and prmcat.entity_type='node' AND prmcat.deleted=0");
  $query->leftJoin('field_revision_field_is_popular','pop',"n.nid = pop.entity_id and pop.entity_type='node' AND pop.deleted=0");

  $query->leftJoin('field_data_field_category','cat',"n.nid = cat.entity_id and cat.entity_type='node' AND cat.deleted=0");
  $query->leftJoin('field_data_field_url','url',"n.nid = url.entity_id and url.entity_type='node' AND url.deleted=0");
  $query->leftJoin('weight_weights','weight',"n.nid = weight.entity_id");
  $query->leftJoin('field_data_field_tracking_url','tu',"n.nid = tu.entity_id and tu.entity_type='node' AND tu.deleted=0");
  $query->fields('tu', array('field_tracking_url_value'));
  $query->leftJoin('field_collection_item','fci',"tu.field_tracking_url_value = fci.item_id");

  $query->leftJoin('field_data_field_url_part1','p1',"p1.entity_id = tu.field_tracking_url_value");
  $query->leftJoin('field_data_field_url_part2','p2',"p2.entity_id = tu.field_tracking_url_value");
  $query->leftJoin('field_data_field_url_part3','p3',"p3.entity_id = tu.field_tracking_url_value");
  $query->leftJoin('field_data_field_url_part4','p4',"p4.entity_id = tu.field_tracking_url_value");
  $query->fields('p1', array('field_url_part1_value'));
  $query->fields('p2', array('field_url_part2_value'));
  $query->fields('p3', array('field_url_part3_value'));
  $query->fields('p4', array('field_url_part4_value'));
  $query->fields('url', array('field_url_value'));
  $query->fields('dt', array('field_display_text_value'));
  $query->fields('img', array('field_image_fid'));
  $query->fields('pop', array('field_is_popular_value'));
  $query->fields('soi', array('field_url_site_of_interest_value'));
  $query->addExpression('GROUP_CONCAT(prmcat.field_primary_category_tid)', 'field_primary_category_tid');

  $query->condition('n.status','1');
  $query->condition('n.type', 'retailers', '=');
  $query->condition('pop.field_is_popular_value', '1', '=');
  if ($matching_node->nid) {
    $query->condition('n.nid', $matching_node['nid'], '<>');
  }
  $query->condition('cntry.field_country_tid', array(4), 'IN');
  $query->condition('fd.field_type_tid', CORP_RETAILERS_PARTNER_TID, '=');
  $query->orderBy('weight.weight');
  $query->orderBy('url.field_url_value');
  $query->groupBy('n.nid');

  $result = $query->execute();
  while($row = $result->fetchObject()) {
    $return['most_populars'][] = $row;
  }
  return $return;
}

function corp_retailers_get_matching($url) {
  $return = array();
  $query = db_select('node','n')
      ->fields('n', array('nid','title'));
  $query->leftJoin('field_data_field_url','url',"n.nid = url.entity_id and url.entity_type='node' AND url.deleted=0");
  $query->leftJoin('field_data_field_type','fd',"n.nid = fd.entity_id and fd.entity_type='node' AND fd.deleted=0");
  $query->leftJoin('field_data_field_url_site_of_interest','soi',"n.nid = soi.entity_id and soi.entity_type='node' AND soi.deleted=0");
  $query->leftJoin('field_data_field_country','cntry',"n.nid = cntry.entity_id and cntry.entity_type='node' AND cntry.deleted=0");
  $query->leftJoin('field_data_field_category','cat',"n.nid = cat.entity_id and cat.entity_type='node' AND cat.deleted=0");
  $query->leftJoin('field_data_field_primary_category','prmcat',"n.nid = prmcat.entity_id and prmcat.entity_type='node' AND prmcat.deleted=0");
  $query->leftJoin('field_data_field_display_text','dt',"n.nid = dt.entity_id and dt.entity_type='node' AND dt.deleted=0");
  $query->leftJoin('field_data_field_tracking_url','tu',"n.nid = tu.entity_id and tu.entity_type='node' AND tu.deleted=0");
  $query->leftJoin('field_revision_field_is_popular','pop',"n.nid = pop.entity_id and pop.entity_type='node' AND pop.deleted=0");
  $query->leftJoin('field_collection_item','fci',"tu.field_tracking_url_value = fci.item_id");
  $query->leftJoin('field_data_field_url_part1','p1',"p1.entity_id = tu.field_tracking_url_value");
  $query->leftJoin('field_data_field_url_part2','p2',"p2.entity_id = tu.field_tracking_url_value");
  $query->leftJoin('field_data_field_url_part3','p3',"p3.entity_id = tu.field_tracking_url_value");
  $query->leftJoin('field_data_field_url_part4','p4',"p4.entity_id = tu.field_tracking_url_value");
  $query->fields('tu', array('field_tracking_url_value'));
  $query->fields('p1', array('field_url_part1_value'));
  $query->fields('p2', array('field_url_part2_value'));
  $query->fields('p3', array('field_url_part3_value'));
  $query->fields('p4', array('field_url_part4_value'));

  $query->fields('fd',array('field_type_tid'));
  $query->fields('url', array('field_url_value'));
  $query->fields('soi', array('field_url_site_of_interest_value'));
  $query->fields('dt', array('field_display_text_value'));
  $query->fields('pop', array('field_is_popular_value'));
  $query->addExpression('GROUP_CONCAT(cntry.field_country_tid)', 'field_country_tid');
  $query->addExpression('GROUP_CONCAT(cat.field_category_tid)', 'field_category_tid');
  $query->addExpression('GROUP_CONCAT(prmcat.field_primary_category_tid)', 'field_primary_category_tid');

  $query->condition('n.status','1');
  $query->condition('n.type', array('sites_of_interest','retailers'), 'IN');
  $query->where('((lower(url.field_url_value) = :arg) OR soi.field_url_site_of_interest_value = :arg1)',
      array(':arg' => $url, ':arg1'=>$url));

  #echo $query;exit;
  return $query->execute()->fetchObject();

}



function corp_retailers_make_url($row, $input_url, $redirect, $uid2) {
  $url = '';
  if ((user_is_anonymous())) {
    return url('login_register', array('attributes'=>array('class'=>'colorbox_form', 'id'=>'colorbox_form')));
  }
  if(isset($row->field_url_part1_value)) {
    $url = $row->field_url_part1_value;
  }
  else {
    $url ='http://'. $input_url;
  }

  if(strtolower($row->field_url_value) == $input_url) {
    $url_part1 = isset ($row->field_url_part1_value) ? $row->field_url_part1_value : '';
    $url_part2 = isset ($row->field_url_part2_value) ? $row->field_url_part2_value : '';
    $url_part3 = isset ($row->field_url_part3_value) ? $row->field_url_part3_value : '';
    $url_part4 = isset ($row->field_url_part4_value) ? $row->field_url_part4_value : '';

    $link_url = url($url);
    $query = '&uid=' . $user->uid . '&uid2=' . $uid2 . '&redirect=' . urlencode($redirect . $url_part2 . $url_part3 . $url_part4);
    $url = $link_url.'?'.$query;
  }
  return $url;
}


function corp_retailers_page_alter(&$page) {
  if (arg(0) =="retailers-partners-list1") {
    foreach (element_children($page) as $region) {
      $page[$region]['#access'] = ($region == 'content');
    }
  }
}